receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://0.0.0.0:4200"
            - "http://0.0.0.0:5173"
            - "http://localhost:4200"
            - "http://localhost:5173"
            - "http://localhost:3001"
            - "http://0.0.0.0:8081"
            - "http://0.0.0.0:3001"
          allowed_headers:
            - "Access-Control-Request-Headers"
            - "Access-Control-Request-Method"
            - "content-type"
            - "Origin"
            -
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: https://api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"

service:
  telemetry:
    logs:
  pipelines:
    traces:
      receivers: [otlp]
      #processors: [symbolicator, batch]
      processors: [batch]
      exporters: [debug, otlp]
